---
# -- The global namespace containes some globally used variables used in patterns
# @default -- depends on the individual settings
global:
  # -- Setting the enforces openshift templates for the vault chart
  openshift: true
  # -- The DNS entry for the cluster the chart is being rendered on with the apps. prefix
  localClusterDomain: apps.foo.cluster.com

# -- A number of settings passed down to the vault subchart
# @default -- depends on the individual settings
vault:
  injector:
    # -- Vault agent injection support
    enabled: false
  ui:
    # -- Vault UI support
    enabled: true
    activeVaultPodOnly: false

  server:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
    # -- Additional environment variables injected in the vault pod
    # -- Base configuration for the standalone vault server
    extraEnvironmentVars:
      VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      VAULT_ADDR: https://127.0.0.1:8200
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
        setNodeId: false
      config: |
        ui = true
        listener "tcp" {
          tls_disable = false
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-secret/tls.crt"
          tls_key_file = "/vault/userconfig/vault-secret/tls.key"
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
          }
        }
        service_registration "kubernetes" {}

    # -- Extra volumes that are automatically mounted in the vault pod under /vault/userconfig/<name>
    extraVolumes:
    - type: secret
      name: vault-secret

    service:
      # -- Enables an associated k8s service when running the vault
      enabled: true
      active:
        # -- Annotation to inject a secret called `vault-secret` to the nonha service
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: vault-active-secret
      nonha:
        # -- Annotation to inject a secret called `vault-secret` to the nonha service
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: vault-secret
      internal:
        # -- Annotation to inject a secret called `vault-secret` to the internal service
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: vault-secret-internal
    route:
      host: null
      activeService: true
      # -- Enable route support when exposing the vault
      enabled: true
      tls:
        # We cannot use passthrough because you'd be talking to
        # https://vault-vault.apps.mcg-hub.blueprints.rhecoeng.com but you'd
        # get vault.vault.svc/vault.vault.svc.cluster.local
        # -- Termination type of the vault route
        termination: "edge"
    image:
      # -- Where to fetch the vault images from
      repository: "registry.connect.redhat.com/hashicorp/vault"
      # -- Tag to use for the vault image
      tag: "1.18.3-ubi"
